### ISSUE TITLE
UDM hook logs password hashes

### ISSUE THREAD

**Issue by spaceone** [Z-Hub/kopano4ucs#3]
The UDM hook logs password hashes with INFO level. This is a security issue.

univention/admin/hooks.d/kopano4ucsRole.py

**Comment by fbartels** [comment]
Thanks for the review @spaceone. What do you propose. Remove the log line completely, or move it to e.g. debug logging?

**Comment by spaceone** [comment]
I would propose to remove that at all.
How often did we need it to debug something in these modules? Not often or none at all.
If there is a bug we often need to add a debugger to find the real issue.
Many things can also be found by just looking at the source code if one has knowledge about it.
